version: "3"
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    volumes:
      - ../volume/jenkins:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"