apiVersion: v1
kind: PersistentVolume
metadata:
  name: maven-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/c/Users/alaya/.m2/repository"